var ServerFactory = function(){
    var server = function (){
        return MonitorServerStub();
    };
    return {
        getServer : server
    };
}();
var MonitorServerStub = function () {
	
	/* months for date string */
    var monthNames = [
                      "January", "February", "March",
                      "April", "May", "June", "July",
                      "August", "September", "October",
                      "November", "December"
                  ];
    /* operations data */
    var operationData = [
        {time:"2016-02-29 11:57", type:"cashoutBet", customer: "Jimmi1", bet:"O/7523244/0007271", duration: 1200, state:"Success", inputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBet adminMode=\"N\" xmlns=\"http://schema.products.sportsbook.openbet.com/bet\"> <customerRef id=\"108993\"/> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <channelRef id=\"M\"/> <cashoutValue amount=\"0.67\"> <currencyRef id=\"GBP\"/> </cashoutValue> </cashoutBet>", outputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBetResponse xmlns=\"http://schema.products.sportsbook.openbet.com/bet\" xmlns:ns2=\"http://schema.products.sportsbook.openbet.com/betcommon\"> <betError code=\"BET_ERROR\" subErrorCode=\"CASHOUT_PENDING\"> <errorDesc>CASHOUT_PENDING</errorDesc> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <cashoutDelay>7</cashoutDelay> <cashoutBetDelayId>18357</cashoutBetDelayId> </betError> <bet receipt=\"O/0108993/0003202\" isSettled=\"N\" isFunded=\"Y\" isConfirmed=\"Y\" timeStamp=\"2016-02-17T15:13:23.000Z\" id=\"129528\" provider=\"OpenBetSports\" addr=\"10.99.30.13\"> <betTypeRef id=\"SGL\"/> <stake amount=\"1.00\" freebet=\"0.00\" stakePerLine=\"1.00\"> <currencyRef id=\"GBP\"/> </stake> <payout potential=\"7.00\" winnings=\"0.00\" refunds=\"0.00\" bonus=\"0.0\"/> <lines number=\"1\" win=\"0\" lose=\"0\" void=\"0\"/> <cashoutValue amount=\"0.67\"/> <partialCashout available=\"Y\"/> <leg result=\"-\" documentId=\"1\"> <ns2:sportsLeg> <ns2:price num=\"6\" den=\"1\" legType=\"-\"> <ns2:priceTypeRef id=\"LP\"/> </ns2:price> <ns2:placeTerms/> <ns2:outcomeCombiRef/> <ns2:winPlaceRef id=\"WIN\"/> <ns2:legPart> <ns2:outcomeRef id=\"136410343\"/> </ns2:legPart> </ns2:sportsLeg> </leg> </bet> </cashoutBetResponse>", stackTrace:""},
        {time:"2016-02-29 11:58", type:"cashoutBet", customer: "Jimmi12", bet:"O/7523244/0007271", duration: 1200, state:"Success", inputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBet adminMode=\"N\" xmlns=\"http://schema.products.sportsbook.openbet.com/bet\"> <customerRef id=\"108993\"/> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <channelRef id=\"M\"/> <cashoutValue amount=\"0.67\"> <currencyRef id=\"GBP\"/> </cashoutValue> </cashoutBet>", outputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBetResponse xmlns=\"http://schema.products.sportsbook.openbet.com/bet\" xmlns:ns2=\"http://schema.products.sportsbook.openbet.com/betcommon\"> <betError code=\"BET_ERROR\" subErrorCode=\"CASHOUT_PENDING\"> <errorDesc>CASHOUT_PENDING</errorDesc> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <cashoutDelay>7</cashoutDelay> <cashoutBetDelayId>18357</cashoutBetDelayId> </betError> <bet receipt=\"O/0108993/0003202\" isSettled=\"N\" isFunded=\"Y\" isConfirmed=\"Y\" timeStamp=\"2016-02-17T15:13:23.000Z\" id=\"129528\" provider=\"OpenBetSports\" addr=\"10.99.30.13\"> <betTypeRef id=\"SGL\"/> <stake amount=\"1.00\" freebet=\"0.00\" stakePerLine=\"1.00\"> <currencyRef id=\"GBP\"/> </stake> <payout potential=\"7.00\" winnings=\"0.00\" refunds=\"0.00\" bonus=\"0.0\"/> <lines number=\"1\" win=\"0\" lose=\"0\" void=\"0\"/> <cashoutValue amount=\"0.67\"/> <partialCashout available=\"Y\"/> <leg result=\"-\" documentId=\"1\"> <ns2:sportsLeg> <ns2:price num=\"6\" den=\"1\" legType=\"-\"> <ns2:priceTypeRef id=\"LP\"/> </ns2:price> <ns2:placeTerms/> <ns2:outcomeCombiRef/> <ns2:winPlaceRef id=\"WIN\"/> <ns2:legPart> <ns2:outcomeRef id=\"136410343\"/> </ns2:legPart> </ns2:sportsLeg> </leg> </bet> </cashoutBetResponse>", stackTrace:""},
        {time:"2016-02-29 11:59", type:"cashoutBet", customer: "Jimmi13", bet:"O/7523244/0007271", duration: 1200, state:"Success", inputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBet adminMode=\"N\" xmlns=\"http://schema.products.sportsbook.openbet.com/bet\"> <customerRef id=\"108993\"/> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <channelRef id=\"M\"/> <cashoutValue amount=\"0.67\"> <currencyRef id=\"GBP\"/> </cashoutValue> </cashoutBet>", outputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBetResponse xmlns=\"http://schema.products.sportsbook.openbet.com/bet\" xmlns:ns2=\"http://schema.products.sportsbook.openbet.com/betcommon\"> <betError code=\"BET_ERROR\" subErrorCode=\"CASHOUT_PENDING\"> <errorDesc>CASHOUT_PENDING</errorDesc> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <cashoutDelay>7</cashoutDelay> <cashoutBetDelayId>18357</cashoutBetDelayId> </betError> <bet receipt=\"O/0108993/0003202\" isSettled=\"N\" isFunded=\"Y\" isConfirmed=\"Y\" timeStamp=\"2016-02-17T15:13:23.000Z\" id=\"129528\" provider=\"OpenBetSports\" addr=\"10.99.30.13\"> <betTypeRef id=\"SGL\"/> <stake amount=\"1.00\" freebet=\"0.00\" stakePerLine=\"1.00\"> <currencyRef id=\"GBP\"/> </stake> <payout potential=\"7.00\" winnings=\"0.00\" refunds=\"0.00\" bonus=\"0.0\"/> <lines number=\"1\" win=\"0\" lose=\"0\" void=\"0\"/> <cashoutValue amount=\"0.67\"/> <partialCashout available=\"Y\"/> <leg result=\"-\" documentId=\"1\"> <ns2:sportsLeg> <ns2:price num=\"6\" den=\"1\" legType=\"-\"> <ns2:priceTypeRef id=\"LP\"/> </ns2:price> <ns2:placeTerms/> <ns2:outcomeCombiRef/> <ns2:winPlaceRef id=\"WIN\"/> <ns2:legPart> <ns2:outcomeRef id=\"136410343\"/> </ns2:legPart> </ns2:sportsLeg> </leg> </bet> </cashoutBetResponse>", stackTrace:""},
        {time:"2016-02-29 12:57", type:"cashoutBet", customer: "Jimmi14", bet:"O/7523244/0007271", duration: 1200, state:"Success", inputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBet adminMode=\"N\" xmlns=\"http://schema.products.sportsbook.openbet.com/bet\"> <customerRef id=\"108993\"/> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <channelRef id=\"M\"/> <cashoutValue amount=\"0.67\"> <currencyRef id=\"GBP\"/> </cashoutValue> </cashoutBet>", outputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBetResponse xmlns=\"http://schema.products.sportsbook.openbet.com/bet\" xmlns:ns2=\"http://schema.products.sportsbook.openbet.com/betcommon\"> <betError code=\"BET_ERROR\" subErrorCode=\"CASHOUT_PENDING\"> <errorDesc>CASHOUT_PENDING</errorDesc> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <cashoutDelay>7</cashoutDelay> <cashoutBetDelayId>18357</cashoutBetDelayId> </betError> <bet receipt=\"O/0108993/0003202\" isSettled=\"N\" isFunded=\"Y\" isConfirmed=\"Y\" timeStamp=\"2016-02-17T15:13:23.000Z\" id=\"129528\" provider=\"OpenBetSports\" addr=\"10.99.30.13\"> <betTypeRef id=\"SGL\"/> <stake amount=\"1.00\" freebet=\"0.00\" stakePerLine=\"1.00\"> <currencyRef id=\"GBP\"/> </stake> <payout potential=\"7.00\" winnings=\"0.00\" refunds=\"0.00\" bonus=\"0.0\"/> <lines number=\"1\" win=\"0\" lose=\"0\" void=\"0\"/> <cashoutValue amount=\"0.67\"/> <partialCashout available=\"Y\"/> <leg result=\"-\" documentId=\"1\"> <ns2:sportsLeg> <ns2:price num=\"6\" den=\"1\" legType=\"-\"> <ns2:priceTypeRef id=\"LP\"/> </ns2:price> <ns2:placeTerms/> <ns2:outcomeCombiRef/> <ns2:winPlaceRef id=\"WIN\"/> <ns2:legPart> <ns2:outcomeRef id=\"136410343\"/> </ns2:legPart> </ns2:sportsLeg> </leg> </bet> </cashoutBetResponse>", stackTrace:""},
        {time:"2016-02-29 13:57", type:"readBet", customer: "Jimmi15", bet:"O/7523244/0007271", duration: 1200, state:"Success", inputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBet adminMode=\"N\" xmlns=\"http://schema.products.sportsbook.openbet.com/bet\"> <customerRef id=\"108993\"/> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <channelRef id=\"M\"/> <cashoutValue amount=\"0.67\"> <currencyRef id=\"GBP\"/> </cashoutValue> </cashoutBet>", outputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBetResponse xmlns=\"http://schema.products.sportsbook.openbet.com/bet\" xmlns:ns2=\"http://schema.products.sportsbook.openbet.com/betcommon\"> <betError code=\"BET_ERROR\" subErrorCode=\"CASHOUT_PENDING\"> <errorDesc>CASHOUT_PENDING</errorDesc> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <cashoutDelay>7</cashoutDelay> <cashoutBetDelayId>18357</cashoutBetDelayId> </betError> <bet receipt=\"O/0108993/0003202\" isSettled=\"N\" isFunded=\"Y\" isConfirmed=\"Y\" timeStamp=\"2016-02-17T15:13:23.000Z\" id=\"129528\" provider=\"OpenBetSports\" addr=\"10.99.30.13\"> <betTypeRef id=\"SGL\"/> <stake amount=\"1.00\" freebet=\"0.00\" stakePerLine=\"1.00\"> <currencyRef id=\"GBP\"/> </stake> <payout potential=\"7.00\" winnings=\"0.00\" refunds=\"0.00\" bonus=\"0.0\"/> <lines number=\"1\" win=\"0\" lose=\"0\" void=\"0\"/> <cashoutValue amount=\"0.67\"/> <partialCashout available=\"Y\"/> <leg result=\"-\" documentId=\"1\"> <ns2:sportsLeg> <ns2:price num=\"6\" den=\"1\" legType=\"-\"> <ns2:priceTypeRef id=\"LP\"/> </ns2:price> <ns2:placeTerms/> <ns2:outcomeCombiRef/> <ns2:winPlaceRef id=\"WIN\"/> <ns2:legPart> <ns2:outcomeRef id=\"136410343\"/> </ns2:legPart> </ns2:sportsLeg> </leg> </bet> </cashoutBetResponse>", stackTrace:""},
        {time:"2016-02-29 14:57", type:"cashoutBet", customer: "Jimmi16", bet:"O/7523244/0007271", duration: 1200, state:"Success", inputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBet adminMode=\"N\" xmlns=\"http://schema.products.sportsbook.openbet.com/bet\"> <customerRef id=\"108993\"/> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <channelRef id=\"M\"/> <cashoutValue amount=\"0.67\"> <currencyRef id=\"GBP\"/> </cashoutValue> </cashoutBet>", outputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBetResponse xmlns=\"http://schema.products.sportsbook.openbet.com/bet\" xmlns:ns2=\"http://schema.products.sportsbook.openbet.com/betcommon\"> <betError code=\"BET_ERROR\" subErrorCode=\"CASHOUT_PENDING\"> <errorDesc>CASHOUT_PENDING</errorDesc> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <cashoutDelay>7</cashoutDelay> <cashoutBetDelayId>18357</cashoutBetDelayId> </betError> <bet receipt=\"O/0108993/0003202\" isSettled=\"N\" isFunded=\"Y\" isConfirmed=\"Y\" timeStamp=\"2016-02-17T15:13:23.000Z\" id=\"129528\" provider=\"OpenBetSports\" addr=\"10.99.30.13\"> <betTypeRef id=\"SGL\"/> <stake amount=\"1.00\" freebet=\"0.00\" stakePerLine=\"1.00\"> <currencyRef id=\"GBP\"/> </stake> <payout potential=\"7.00\" winnings=\"0.00\" refunds=\"0.00\" bonus=\"0.0\"/> <lines number=\"1\" win=\"0\" lose=\"0\" void=\"0\"/> <cashoutValue amount=\"0.67\"/> <partialCashout available=\"Y\"/> <leg result=\"-\" documentId=\"1\"> <ns2:sportsLeg> <ns2:price num=\"6\" den=\"1\" legType=\"-\"> <ns2:priceTypeRef id=\"LP\"/> </ns2:price> <ns2:placeTerms/> <ns2:outcomeCombiRef/> <ns2:winPlaceRef id=\"WIN\"/> <ns2:legPart> <ns2:outcomeRef id=\"136410343\"/> </ns2:legPart> </ns2:sportsLeg> </leg> </bet> </cashoutBetResponse>", stackTrace:""},
        {time:"2016-02-29 15:57", type:"cashoutBet", customer: "Jimmi17", bet:"O/7523244/0007271", duration: 1200, state:"Success", inputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBet adminMode=\"N\" xmlns=\"http://schema.products.sportsbook.openbet.com/bet\"> <customerRef id=\"108993\"/> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <channelRef id=\"M\"/> <cashoutValue amount=\"0.67\"> <currencyRef id=\"GBP\"/> </cashoutValue> </cashoutBet>", outputXML:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <cashoutBetResponse xmlns=\"http://schema.products.sportsbook.openbet.com/bet\" xmlns:ns2=\"http://schema.products.sportsbook.openbet.com/betcommon\"> <betError code=\"BET_ERROR\" subErrorCode=\"CASHOUT_PENDING\"> <errorDesc>CASHOUT_PENDING</errorDesc> <betRef id=\"129528\" provider=\"OpenBetSports\"/> <cashoutDelay>7</cashoutDelay> <cashoutBetDelayId>18357</cashoutBetDelayId> </betError> <bet receipt=\"O/0108993/0003202\" isSettled=\"N\" isFunded=\"Y\" isConfirmed=\"Y\" timeStamp=\"2016-02-17T15:13:23.000Z\" id=\"129528\" provider=\"OpenBetSports\" addr=\"10.99.30.13\"> <betTypeRef id=\"SGL\"/> <stake amount=\"1.00\" freebet=\"0.00\" stakePerLine=\"1.00\"> <currencyRef id=\"GBP\"/> </stake> <payout potential=\"7.00\" winnings=\"0.00\" refunds=\"0.00\" bonus=\"0.0\"/> <lines number=\"1\" win=\"0\" lose=\"0\" void=\"0\"/> <cashoutValue amount=\"0.67\"/> <partialCashout available=\"Y\"/> <leg result=\"-\" documentId=\"1\"> <ns2:sportsLeg> <ns2:price num=\"6\" den=\"1\" legType=\"-\"> <ns2:priceTypeRef id=\"LP\"/> </ns2:price> <ns2:placeTerms/> <ns2:outcomeCombiRef/> <ns2:winPlaceRef id=\"WIN\"/> <ns2:legPart> <ns2:outcomeRef id=\"136410343\"/> </ns2:legPart> </ns2:sportsLeg> </leg> </bet> </cashoutBetResponse>", stackTrace:""}
    ];
    /* the types of valid operations */
    var operationTypes = [
      "cashoutBet"  ,
      "readBet"
    ];

    var getOperationsData = function(criteria, processAnswer){
        processAnswer(operationData);
    };
    var getOperationTypes = function(processAnswer){
        processAnswer(operationTypes);
    };
    var getOperationsCount = function(criteria, processAnswer){
        processAnswer((Math.random() * 1000).toFixed(0));
    }
    var getMonths = function(){
        return monthNames;
    };
	
	return {
                getMonths: getMonths,
		getOperationsData: getOperationsData,
        getOperationsCount: getOperationsCount,
		getOperationTypes: getOperationTypes

	};
};